### ISSUE TITLE
new funtional: shared memory -> sockets?

### ISSUE THREAD

**Issue by gogonaft** [borzunov/remoteink#5] opened 2016-12-28 04:14 UTC
Hi, I wonder could X shared memory code be re-written so that socket transmission is used instead?

I'm trying to get remoteink working over SSH and it does not work with shm-* functions.
It works nicely if I run X11 on host itself, though.

UPD: looks like the problem is not with shared memory but with remoteinkd server itself. No additional error is thrown if shm* execs were disabled in code. Server running showing black screen on client.

**Comment by borzunov** [comment] 2016-12-31 22:41
Hi @gogonaft,

I think I've fixed this issue in a2bc570, so you can try a new server version from master.

Actually, receiving of a screenshot via sockets has already been implemented, but detection of the fact that shared memory is unavailable didn't work properly in this case.

**Comment by gogonaft** [comment] 2017-01-02 04:02
Thank for quick reaction, @borzunov. But it looks like it does the same thing to me: saying error about shared mem and exits. What is the best way to troubleshoot it?
`Jan  1 19:59:09 raspberrypi remoteinkd: Failed to attach shared memory
Jan  1 19:59:09 raspberrypi remoteinkd: Unknown key "KP_Delete" in shortcut "Ctrl+Alt+KP_Delete"`

Workaround is to use x11vnc.

**Comment by borzunov** [comment] 2017-01-02 12:19
Unfortunately, it isn't clear from the logs, but `Failed to attach shared memory` message is just a non-critical notice, and `Unknown key "KP_Delete" in shortcut "Ctrl+Alt+KP_Delete"` is an actual reason of failure.

I suggest trying to comment out a line with a mention of `KP_Delete` key in `/etc/remoteinkd/config.ini`. If this helps, you can leave the shortcut disabled or rebind the action to another key.

**Comment by gogonaft** [comment] 2017-01-02 18:55
Did not think shortcuts would cause this. I've commented them and remoteinkd started. 
But, it's showing black screen only if I try through "ssh -X"(tried with xclock, lxterminal, lxsession).

**Comment by borzunov** [comment] 2017-01-02 19:09
The following configuration works for me:

1. I have two machines, one runs my desktop environment (machine A, Ubuntu), and another will run remoteinkd (machine B, Fedora).

2. I can connect from machine A to machine B through `ssh -X` and start remoteinkd there using:

        sudo -E remoteinkd start

3. Then I can connect from the reader to machine B and see the desktop of machine A.

Is this what you are trying to do, or how does your configuration differ?

**Comment by gogonaft** [comment] 2017-01-02 19:24
Using it in exactly same way, only that A=MacOS. I don't have problem seeing X apps opened via this ssh-session on A, but only black screen is on Reader.
`Jan  2 11:20:11 raspberrypi remoteinkd: Monitor resolution: 1680x1027
Jan  2 11:20:11 raspberrypi remoteinkd: Server listens on 0.0.0.0:9312
Jan  2 11:20:20 raspberrypi remoteinkd: Accepted client connection from 192.168.X.X
Jan  2 11:20:20 raspberrypi remoteinkd: Reader resolution: 800x600`

**Comment by borzunov** [comment] 2017-01-02 20:36
Try to run an utility like `scrot` inside the SSH connection to B. It will save a screenshot of the desktop to a file in the current directory in B.  Does this screenshot contain anything? Will it contain anything if you run `xclock` simultaneously in the same SSH connection?

**Comment by gogonaft** [comment] 2017-01-03 06:28
scrot always gives blank screen inside SSH session to B. Looks like problem somewhere on my side.

**Comment by borzunov** [comment] 2017-01-03 17:11
As far as I understood, Mac OS X native apps don't use X11, and there's no opportunity to make a screenshot of these apps via X11. That's a reason why scrot and remoteinkd (which uses only X11 to capture the screen) don't work in this case.

**Comment by gogonaft** [comment] 2017-01-04 02:00
MacOS has port of X11 and it is used for X apps. Somehow scrot not capturing that screen though.

**Comment by borzunov** [comment] 2017-01-04 02:07
Yeah, but I suppose this port is not able to capture the screen with non-X11 apps (these apps may use other screen buffers, which are inaccessible from X11).

**Comment by borzunov** [comment] 2017-01-27 23:29
Since it doesn't look that the problem is in remoteink app, I will close this for now. Don't hesitate to open another issue if you find other problems related to remoteink.

**Closed as completed by borzunov** 2017-01-27 23:29 UTC
